import { Resend } from "resend";
import { ENV } from "./env";

let resendClient: Resend | null = null;

function getResend(): Resend {
  if (!resendClient) {
    resendClient = new Resend(ENV.resendApiKey);
  }
  return resendClient;
}

export type SendReportEmailParams = {
  to: string;
  childName: string;
  language: "fr" | "en" | "ar";
  pdfBuffer: Buffer;
  reportDate: string;
};

export async function sendReportEmail({
  to,
  childName,
  language,
  pdfBuffer,
  reportDate,
}: SendReportEmailParams): Promise<{ success: boolean; error?: string }> {
  if (!ENV.resendApiKey) {
    return { success: false, error: "RESEND_API_KEY not configured" };
  }

  const subjects: Record<string, string> = {
    fr: `Rapport de santé AlleNest – ${childName}`,
    en: `AlleNest Health Report – ${childName}`,
    ar: `تقرير صحة AlleNest – ${childName}`,
  };

  const bodies: Record<string, string> = {
    fr: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <div style="background: linear-gradient(135deg, #4FC3F7, #0288D1); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px;">AlleNest</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0;">Votre compagnon de santé pédiatrique</p>
        </div>
        <div style="background: #f9fafb; padding: 24px; border-radius: 0 0 12px 12px;">
          <h2 style="color: #0288D1;">Rapport de santé</h2>
          <p>Bonjour,</p>
          <p>Veuillez trouver ci-joint le rapport de santé de <strong>${childName}</strong>, généré le <strong>${reportDate}</strong> depuis l'application AlleNest.</p>
          <p>Ce rapport contient :</p>
          <ul>
            <li>Le profil de l'enfant</li>
            <li>L'historique des symptômes (30 derniers jours)</li>
            <li>Le journal des repas (30 derniers jours)</li>
            <li>La liste des médecins</li>
          </ul>
          <p style="color: #999; font-size: 12px; margin-top: 24px;">
            Ce rapport est à titre informatif et ne remplace pas un avis médical professionnel.
          </p>
          <p style="color: #999; font-size: 12px;">Généré par AlleNest – Application de suivi de santé pédiatrique</p>
        </div>
      </div>
    `,
    en: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <div style="background: linear-gradient(135deg, #4FC3F7, #0288D1); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px;">AlleNest</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0;">Your smart child health companion</p>
        </div>
        <div style="background: #f9fafb; padding: 24px; border-radius: 0 0 12px 12px;">
          <h2 style="color: #0288D1;">Health Report</h2>
          <p>Hello,</p>
          <p>Please find attached the health report for <strong>${childName}</strong>, generated on <strong>${reportDate}</strong> from the AlleNest app.</p>
          <p>This report includes:</p>
          <ul>
            <li>Child profile</li>
            <li>Symptom history (last 30 days)</li>
            <li>Meal journal (last 30 days)</li>
            <li>Doctors list</li>
          </ul>
          <p style="color: #999; font-size: 12px; margin-top: 24px;">
            This report is for informational purposes and does not replace professional medical advice.
          </p>
          <p style="color: #999; font-size: 12px;">Generated by AlleNest – Pediatric Health Tracking App</p>
        </div>
      </div>
    `,
    ar: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; direction: rtl;">
        <div style="background: linear-gradient(135deg, #4FC3F7, #0288D1); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px;">AlleNest</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0;">رفيقك الذكي لصحة طفلك</p>
        </div>
        <div style="background: #f9fafb; padding: 24px; border-radius: 0 0 12px 12px;">
          <h2 style="color: #0288D1;">تقرير الصحة</h2>
          <p>مرحباً،</p>
          <p>يرجى الاطلاع على تقرير صحة <strong>${childName}</strong> المرفق، الصادر بتاريخ <strong>${reportDate}</strong> من تطبيق AlleNest.</p>
          <p>يتضمن هذا التقرير:</p>
          <ul>
            <li>ملف الطفل</li>
            <li>سجل الأعراض (آخر 30 يومًا)</li>
            <li>سجل الوجبات (آخر 30 يومًا)</li>
            <li>قائمة الأطباء</li>
          </ul>
          <p style="color: #999; font-size: 12px; margin-top: 24px;">
            هذا التقرير لأغراض إعلامية ولا يحل محل الاستشارة الطبية المتخصصة.
          </p>
          <p style="color: #999; font-size: 12px;">تم إنشاؤه بواسطة AlleNest – تطبيق تتبع صحة الأطفال</p>
        </div>
      </div>
    `,
  };

  try {
    const resend = getResend();
    const { error } = await resend.emails.send({
      from: "AlleNest <onboarding@resend.dev>",
      to: [to],
      subject: subjects[language] ?? subjects.fr,
      html: bodies[language] ?? bodies.fr,
      attachments: [
        {
          filename: `allenest-report-${childName.toLowerCase().replace(/\s+/g, "-")}-${reportDate}.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    if (error) {
      return { success: false, error: error.message };
    }
    return { success: true };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return { success: false, error: message };
  }
}
