import PDFDocument from "pdfkit";

export type ReportData = {
  childName: string;
  birthDate?: string | null;
  gender?: string | null;
  bloodType?: string | null;
  allergies?: string[];
  reportDate: string;
  language: "fr" | "en" | "ar";
  symptoms: Array<{
    symptomType: string;
    severity: number;
    notes?: string | null;
    createdAt: Date | string;
  }>;
  meals: Array<{
    foodName: string;
    mealType?: string | null;
    notes?: string | null;
    createdAt: Date | string;
  }>;
  doctors: Array<{
    name: string;
    specialty?: string | null;
    phone?: string | null;
    email?: string | null;
  }>;
};

const LABELS = {
  fr: {
    title: "Rapport de Santé",
    subtitle: "Application AlleNest – Suivi de santé pédiatrique",
    childProfile: "Profil de l'Enfant",
    name: "Nom",
    birthDate: "Date de naissance",
    gender: "Genre",
    bloodType: "Groupe sanguin",
    allergies: "Allergies",
    symptoms: "Historique des Symptômes (30 derniers jours)",
    meals: "Journal des Repas (30 derniers jours)",
    doctors: "Médecins",
    date: "Date",
    severity: "Sévérité",
    type: "Type",
    notes: "Notes",
    specialty: "Spécialité",
    phone: "Téléphone",
    email: "Email",
    noData: "Aucune donnée disponible",
    disclaimer: "Ce rapport est à titre informatif et ne remplace pas un avis médical professionnel.",
    generatedBy: "Généré par AlleNest",
    reportDate: "Date du rapport",
  },
  en: {
    title: "Health Report",
    subtitle: "AlleNest App – Pediatric Health Tracking",
    childProfile: "Child Profile",
    name: "Name",
    birthDate: "Date of birth",
    gender: "Gender",
    bloodType: "Blood type",
    allergies: "Allergies",
    symptoms: "Symptom History (Last 30 days)",
    meals: "Meal Journal (Last 30 days)",
    doctors: "Doctors",
    date: "Date",
    severity: "Severity",
    type: "Type",
    notes: "Notes",
    specialty: "Specialty",
    phone: "Phone",
    email: "Email",
    noData: "No data available",
    disclaimer: "This report is for informational purposes and does not replace professional medical advice.",
    generatedBy: "Generated by AlleNest",
    reportDate: "Report date",
  },
  ar: {
    title: "تقرير الصحة",
    subtitle: "تطبيق AlleNest – تتبع صحة الأطفال",
    childProfile: "ملف الطفل",
    name: "الاسم",
    birthDate: "تاريخ الميلاد",
    gender: "الجنس",
    bloodType: "فصيلة الدم",
    allergies: "الحساسيات",
    symptoms: "سجل الأعراض (آخر 30 يومًا)",
    meals: "سجل الوجبات (آخر 30 يومًا)",
    doctors: "الأطباء",
    date: "التاريخ",
    severity: "الشدة",
    type: "النوع",
    notes: "ملاحظات",
    specialty: "التخصص",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    noData: "لا توجد بيانات متاحة",
    disclaimer: "هذا التقرير لأغراض إعلامية ولا يحل محل الاستشارة الطبية المتخصصة.",
    generatedBy: "تم إنشاؤه بواسطة AlleNest",
    reportDate: "تاريخ التقرير",
  },
};

function formatDate(date: Date | string, language: string): string {
  const d = typeof date === "string" ? new Date(date) : date;
  if (isNaN(d.getTime())) return String(date);
  return d.toLocaleDateString(
    language === "fr" ? "fr-FR" : language === "ar" ? "ar-DZ" : "en-US",
    { year: "numeric", month: "long", day: "numeric" }
  );
}

export function generateReportPDF(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const L = LABELS[data.language] ?? LABELS.fr;
    const PRIMARY = "#0288D1";
    const SECONDARY = "#F8BBD0";
    const GRAY = "#666666";
    const LIGHT_GRAY = "#f5f5f5";

    // ─── HEADER ────────────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 90).fill(PRIMARY);
    doc.fillColor("white").fontSize(22).font("Helvetica-Bold")
      .text("AlleNest", 50, 25);
    doc.fontSize(11).font("Helvetica")
      .text(L.subtitle, 50, 52);
    doc.fontSize(10)
      .text(`${L.reportDate}: ${data.reportDate}`, 50, 68);

    doc.moveDown(3);

    // ─── CHILD PROFILE ─────────────────────────────────────────────────────────
    doc.fillColor(PRIMARY).fontSize(14).font("Helvetica-Bold")
      .text(L.childProfile, 50, doc.y);
    doc.moveTo(50, doc.y + 2).lineTo(545, doc.y + 2).strokeColor(PRIMARY).stroke();
    doc.moveDown(0.5);

    const profileRows = [
      [L.name, data.childName],
      ...(data.birthDate ? [[L.birthDate, data.birthDate]] : []),
      ...(data.gender ? [[L.gender, data.gender]] : []),
      ...(data.bloodType ? [[L.bloodType, data.bloodType]] : []),
      ...(data.allergies?.length ? [[L.allergies, data.allergies.join(", ")]] : []),
    ];

    profileRows.forEach(([label, value]) => {
      doc.fillColor(GRAY).fontSize(10).font("Helvetica-Bold")
        .text(`${label}:`, 50, doc.y, { continued: true, width: 150 });
      doc.fillColor("#333").font("Helvetica")
        .text(` ${value}`, { width: 350 });
    });

    doc.moveDown(1.5);

    // ─── SYMPTOMS ──────────────────────────────────────────────────────────────
    doc.fillColor(PRIMARY).fontSize(14).font("Helvetica-Bold")
      .text(L.symptoms, 50, doc.y);
    doc.moveTo(50, doc.y + 2).lineTo(545, doc.y + 2).strokeColor(PRIMARY).stroke();
    doc.moveDown(0.5);

    if (data.symptoms.length === 0) {
      doc.fillColor(GRAY).fontSize(10).font("Helvetica-Oblique")
        .text(L.noData, 50, doc.y);
    } else {
      // Table header
      doc.rect(50, doc.y, 495, 20).fill(LIGHT_GRAY);
      const headerY = doc.y + 4;
      doc.fillColor(GRAY).fontSize(9).font("Helvetica-Bold")
        .text(L.date, 55, headerY, { width: 120 })
        .text(L.type, 180, headerY, { width: 150 })
        .text(L.severity, 335, headerY, { width: 60 })
        .text(L.notes, 400, headerY, { width: 140 });
      doc.moveDown(1.2);

      data.symptoms.slice(0, 20).forEach((s, i) => {
        if (doc.y > 720) { doc.addPage(); }
        const rowY = doc.y;
        if (i % 2 === 0) doc.rect(50, rowY - 2, 495, 18).fill("#fafafa");
        doc.fillColor("#333").fontSize(9).font("Helvetica")
          .text(formatDate(s.createdAt, data.language), 55, rowY, { width: 120 })
          .text(s.symptomType, 180, rowY, { width: 150 })
          .text(`${s.severity}/10`, 335, rowY, { width: 60 })
          .text(s.notes ?? "-", 400, rowY, { width: 140 });
        doc.moveDown(0.8);
      });
    }

    doc.moveDown(1.5);

    // ─── MEALS ─────────────────────────────────────────────────────────────────
    if (doc.y > 650) doc.addPage();

    doc.fillColor(PRIMARY).fontSize(14).font("Helvetica-Bold")
      .text(L.meals, 50, doc.y);
    doc.moveTo(50, doc.y + 2).lineTo(545, doc.y + 2).strokeColor(PRIMARY).stroke();
    doc.moveDown(0.5);

    if (data.meals.length === 0) {
      doc.fillColor(GRAY).fontSize(10).font("Helvetica-Oblique")
        .text(L.noData, 50, doc.y);
    } else {
      doc.rect(50, doc.y, 495, 20).fill(LIGHT_GRAY);
      const mHeaderY = doc.y + 4;
      doc.fillColor(GRAY).fontSize(9).font("Helvetica-Bold")
        .text(L.date, 55, mHeaderY, { width: 120 })
        .text(L.name, 180, mHeaderY, { width: 150 })
        .text(L.type, 335, mHeaderY, { width: 100 })
        .text(L.notes, 440, mHeaderY, { width: 100 });
      doc.moveDown(1.2);

      data.meals.slice(0, 20).forEach((m, i) => {
        if (doc.y > 720) { doc.addPage(); }
        const rowY = doc.y;
        if (i % 2 === 0) doc.rect(50, rowY - 2, 495, 18).fill("#fafafa");
        doc.fillColor("#333").fontSize(9).font("Helvetica")
          .text(formatDate(m.createdAt, data.language), 55, rowY, { width: 120 })
          .text(m.foodName, 180, rowY, { width: 150 })
          .text(m.mealType ?? "-", 335, rowY, { width: 100 })
          .text(m.notes ?? "-", 440, rowY, { width: 100 });
        doc.moveDown(0.8);
      });
    }

    doc.moveDown(1.5);

    // ─── DOCTORS ───────────────────────────────────────────────────────────────
    if (doc.y > 650) doc.addPage();

    doc.fillColor(PRIMARY).fontSize(14).font("Helvetica-Bold")
      .text(L.doctors, 50, doc.y);
    doc.moveTo(50, doc.y + 2).lineTo(545, doc.y + 2).strokeColor(PRIMARY).stroke();
    doc.moveDown(0.5);

    if (data.doctors.length === 0) {
      doc.fillColor(GRAY).fontSize(10).font("Helvetica-Oblique")
        .text(L.noData, 50, doc.y);
    } else {
      data.doctors.forEach((d) => {
        if (doc.y > 720) { doc.addPage(); }
        doc.fillColor("#333").fontSize(10).font("Helvetica-Bold")
          .text(d.name, 50, doc.y);
        if (d.specialty) {
          doc.fillColor(GRAY).fontSize(9).font("Helvetica")
            .text(`${L.specialty}: ${d.specialty}`, 50, doc.y);
        }
        if (d.phone) {
          doc.text(`${L.phone}: ${d.phone}`, 50, doc.y);
        }
        if (d.email) {
          doc.text(`${L.email}: ${d.email}`, 50, doc.y);
        }
        doc.moveDown(0.8);
      });
    }

    // ─── FOOTER ────────────────────────────────────────────────────────────────
    const footerY = doc.page.height - 60;
    doc.moveTo(50, footerY).lineTo(545, footerY).strokeColor("#eee").stroke();
    doc.fillColor(GRAY).fontSize(8).font("Helvetica-Oblique")
      .text(L.disclaimer, 50, footerY + 8, { width: 495, align: "center" });
    doc.text(L.generatedBy, 50, footerY + 28, { width: 495, align: "center" });

    doc.end();
  });
}
